package aplicacion_trabajadores;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author Familia
 */
public class jfTrabajadores extends javax.swing.JFrame {
    //ArrayList<Trabajador> listaTrabajadores=new ArrayList<Trabajador>();
    /**
     * Creates new form jfTrabajadores
     */
    public jfTrabajadores() {
        initComponents();
    }
    
    public void limpiarCampos(){
        this.jtID.setText("");
        this.jtNombre.setText("");
        this.jtDireccion.setText("");
        this.jtTelefono.setText("");
        this.jtSueldo.setText("");
        this.lbInfo.setVisible(false);
        this.cbRegiones.setSelectedIndex(0);
        this.jtID.setEditable(true);
    }
    
    public void inicializar(){
        Conector_trabajadores con = new Conector_trabajadores();
        con.connect();
        limpiarCampos();
        con.close();
    }
    
    public void mostrarMensaje(String mensaje){
        this.lbInfo.setVisible(true);
        this.lbInfo.setText(mensaje);
    }
    
    public boolean validarID(int id) throws SQLException{
        
        Conector_trabajadores con = new Conector_trabajadores();
        con.connect();
        ResultSet resultado = null;
            resultado=con.mostrarTrabajadores(id);
            if(null!=resultado){
                while (resultado.next()) {
                    if(id==resultado.getInt("id"))return false;
                }
            }
        return true;
     }
    
    public void actualizar_tabla(){
        Conector_trabajadores con = new Conector_trabajadores();
        con.connect();
        ResultSet resultado = null;
        resultado=con.tomar_tabla();
        if(null!=resultado){
            jTable1.setModel(DbUtils.resultSetToTableModel(resultado));
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbSueldo = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtSueldo = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbRegiones = new javax.swing.JComboBox();
        btBuscar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setText("Ingreso de Funcionarios");

        lbID.setText("ID");

        lbNombre.setText("Nombre");

        lbDireccion.setText("Direccion");

        lbTelefono.setText("Telefono");

        lbSueldo.setText("Sueldo");

        jtID.setText("jTextField1");

        jtNombre.setText("jTextField2");

        jtDireccion.setText("jTextField3");

        jtTelefono.setText("jTextField4");

        jtSueldo.setText("jTextField5");

        btGuardar.setText("Guardar");
        btGuardar.setToolTipText("");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        lbInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfo.setText("INFORMACION");

        btCerrar.setText("Salir");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Region");

        cbRegiones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una region", "Region 1", "Region 2", "Region 3", "Region 4", "Region 5" }));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Direccion", "Telefono", "Sueldo", "Region"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLimpiar)
                            .addComponent(btBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbID)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btGuardar)
                                    .addGap(124, 124, 124)
                                    .addComponent(btCerrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNombre)
                                            .addComponent(lbDireccion))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbTelefono)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(lbSueldo))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtTelefono)
                                        .addComponent(jtSueldo)
                                        .addComponent(cbRegiones, 0, 192, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbID))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDireccion)
                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTelefono)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSueldo)
                            .addComponent(jtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lbInfo)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBorrar)
                            .addComponent(btBuscar))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGuardar)
                            .addComponent(btLimpiar)
                            .addComponent(btCerrar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        try{
            
            String idStr=this.jtID.getText();
            String nombre=jtNombre.getText();
            String direccion=jtDireccion.getText();
            String telefono=jtTelefono.getText();
            String sueldoStr=this.jtSueldo.getText();
            String region=(String)cbRegiones.getSelectedItem();
            
            
            boolean errorIngresoVacio=false;
            if("".equals(idStr))        errorIngresoVacio=true;
            if("".equals(nombre))       errorIngresoVacio=true;
            if("".equals(direccion))    errorIngresoVacio=true;
            if("".equals(telefono))     errorIngresoVacio=true;
            if("".equals(sueldoStr))    errorIngresoVacio=true;
            if(cbRegiones.getSelectedIndex()==0)errorIngresoVacio=true;
            
            if(errorIngresoVacio){
                mostrarMensaje("Debe ingresar todos los campos");
                return;
            }
            
            int id=Integer.parseInt(idStr);
            int sueldo=Integer.parseInt(sueldoStr);
            
            if(validarID(id)){
                Trabajador t=new Trabajador(id, nombre, direccion, telefono, sueldo,region);
             
                Conector_trabajadores con = new Conector_trabajadores();
                con.connect();
                con.saveTrabajador(t);
                con.close();
                limpiarCampos();
                mostrarMensaje("Funcionario Ingresado");
            }else{
                mostrarMensaje("ID no valido");
                
            }
            
            
            
            
        }catch(Exception e){
            
            mostrarMensaje("ID y Sueldo deben ser numericos.");
        }
        actualizar_tabla();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        this.lbInfo.setVisible(false);
        String idStr=jtID.getText();
        if("".equals(idStr)){
            mostrarMensaje("Debe ingresar un ID");
            return;
        }
        try {
            int id=Integer.parseInt(idStr);
            
            Conector_trabajadores con = new Conector_trabajadores();
            con.connect();
            ResultSet resultado = null;
            resultado=con.mostrarTrabajadores(id);
            if(resultado!=null){
                while (resultado.next()) {
                    this.jtID.setEditable(false);
                    jtNombre.setText(resultado.getString("nombre"));
                    jtDireccion.setText(resultado.getString("direccion"));
                    jtTelefono.setText(resultado.getString("telefono"));
                    jtSueldo.setText(Double.toString(resultado.getDouble("sueldo")));
                    
                    ComboBoxModel cbm=this.cbRegiones.getModel();
                    for (int i = 0; i < cbm.getSize(); i++) {
                        if(cbm.getElementAt(i).toString().equals(resultado.getString("region"))){
                            this.cbRegiones.setSelectedIndex(i);
                            return;
                        }
                    }
                    
                    
                }
            }
            con.close();
            limpiarCampos();
            this.jtID.setText(idStr);
            mostrarMensaje("ID no encontrado");
            
            
        } catch (Exception e) {
            mostrarMensaje("ID debe ser numerico");
        }
        
    }//GEN-LAST:event_btBuscarActionPerformed
    
    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        
        this.lbInfo.setVisible(false);
        String idStr=jtID.getText();
        if("".equals(idStr)){
            mostrarMensaje("Debe ingresar un ID");
            return;
        }
        try {
            int id=Integer.parseInt(idStr);
            
            
            
                Conector_trabajadores con = new Conector_trabajadores();
                con.connect();
                ResultSet resultado = null;
                resultado=con.mostrarTrabajadores(id);
                
                if(resultado!=null)
                
                {
                    while (resultado.next()) {
                        if(resultado.getInt("id")==id){
                            con.deleteTrabajador(id);
                            mostrarMensaje("ID eliminado");
                            return;
                        }
                    
                    }
                                
                    
                }
                con.close();
                limpiarCampos();
                this.jtID.setText(idStr);
                mostrarMensaje("ID no encontrado");
            
        } catch (Exception e) {
            mostrarMensaje("ID debe ser numerico");
        }
    }//GEN-LAST:event_btBorrarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox cbRegiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtSueldo;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSueldo;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
